# 개발 환경 전용 설정 파일
services:
  backend:
    # 1. 소스 코드 실시간 동기화 (볼륨 마운트)
    # 로컬 PC의 backend 폴더와 컨테이너 내부의 작업 폴더(/app)를 연결합니다.
    # Dockerfile의 WORKDIR이 /app이라고 가정합니다.
    volumes:
      - ./backend:/app

    # 2. 코드 변경 시 자동 리로드되는 개발용 서버 실행
    # Gunicorn 대신 Uvicorn의 reload 옵션을 사용합니다.
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]